application:
  name: react-training-sacha-house
  port: 3000
  healthPath: /

environments:
  staging:
    domain: staging.react-training.sacha.house
    noIndex: true
  production:
    domain: react-training.sacha.house

resources:
  cpu: 200
  memory: 128
